### ISSUE TITLE
How to test Titan ?

### ISSUE THREAD

**Issue by ChangChihChiang** [Titannet-dao/titan#7]
Hello. 
I'm a beginner and I want to know how to run Titan. Is there a good easy tutorial. Come guide us to use Titan. 
Thanks

**Comment by TitanNet** [comment]
Hi Bro, you can follow this link to get how to run a Titan test node.

https://titannetwork.notion.site/Titan-3463a508339242d4819679f1838204a8?pvs=4
https://github.com/Filecoin-Titan/titan/releases/tag/v0.1.10

**Comment by ChangChihChiang** [comment]
Hello

How do I register the node?

Is it in the program?

**Comment by TitanNet** [comment]
Here are the detailed steps 

https://titannetwork.notion.site/Titan-3463a508339242d4819679f1838204a8?pvs=4

**Comment by ChangChihChiang** [comment]
Hello

Windows’s .exe can‘t run?

Flashback? May I ask how to solve it?

Thank you

**Comment by ChangChihChiang** [comment]
It‘s not a good experience. Tutorial. Too perfunctory

Be ready to make it public.

Thank you

**Comment by ChangChihChiang** [comment]
請問 錯誤？如何排除？
![image](https://github.com/Filecoin-Titan/titan/assets/111222347/fc32ab31-9467-4761-9bd3-e88d3a2394c0)
